-- MySQL Script generated by MySQL Workbench
-- Mon Jul 22 10:10:42 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Monarch
-- -----------------------------------------------------
-- Table storing multiple disease ontology ids for Monarch Initiative

-- -----------------------------------------------------
-- Schema Monarch
--
-- Table storing multiple disease ontology ids for Monarch Initiative
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Monarch` DEFAULT CHARACTER SET utf8 ;
USE `Monarch` ;

-- -----------------------------------------------------
-- Table `Monarch`.`Mesh_entryId`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Monarch`.`Mesh_entryId` (
  `DB` VARCHAR(45) NOT NULL COMMENT 'Name original database/ontology',
  `id` VARCHAR(45) NOT NULL COMMENT 'Disease ontology identifier from Monarch Disease Ontology and EFO.',
  `def` VARCHAR(255) NOT NULL,
  `level` INT NOT NULL,
  PRIMARY KEY (`DB`, `id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Monarch`.`Mesh_parentId`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Monarch`.`Mesh_parentId` (
  `DB` VARCHAR(45) NOT NULL COMMENT 'Database for id',
  `id` VARCHAR(45) NOT NULL COMMENT 'Disease ontology identifier from Monarch Disease Ontology ',
  `pDB` VARCHAR(45) NOT NULL COMMENT 'Name database for parent id',
  `parent` VARCHAR(45) NOT NULL COMMENT 'Parent ontology for id in Monarch Disease Ontology ',
  `origin` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`DB`, `id`),
  CONSTRAINT `fk_table1_entryId1`
    FOREIGN KEY (`DB` , `id`)
    REFERENCES `Monarch`.`Mesh_entryId` (`DB` , `id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Monarch`.`Mesh_idNames`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Monarch`.`Mesh_idNames` (
  `DB` VARCHAR(45) NOT NULL COMMENT 'Name original database',
  `id` VARCHAR(45) NOT NULL COMMENT 'Disease ontology identifier from Monarch Disease Ontology',
  `syn` VARCHAR(45) NOT NULL COMMENT 'Term (synonym or label) to describe the disease',
  `canonical` TINYINT NOT NULL COMMENT 'Current label for the entry',
  PRIMARY KEY (`DB`, `id`),
  CONSTRAINT `fk_table1_entryId2`
    FOREIGN KEY (`DB` , `id`)
    REFERENCES `Monarch`.`Mesh_entryId` (`DB` , `id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Monarch`.`Mesh_sourceFiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Monarch`.`Mesh_sourceFiles` (
  `url` VARCHAR(45) NOT NULL COMMENT 'URL location of source files',
  `current` VARCHAR(45) NOT NULL COMMENT 'Date of the current version of the source files',
  PRIMARY KEY (`url`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
